//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMetricsCalculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeMetricsCalculator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class img2html extends Frame 
        ///{
        ///	static Image im = null;
        ///	static int W = 1, H = 1;
        ///
        ///    	public static void main()
        ///    	{
        ///		Scanner sc= new Scanner(System.in);
        ///        int strFromScaner = sc.nextInt();
        ///		strFromScaner = strFromScaner + &quot; &quot;;
        ///        System.out.println(strFromScaner);
        ///        int number = sc.nextInt();
        ///		if (number == 1)
        ///			System.out.println(number);
        ///		int otherNumber = sc.nextInt(); //do not use
        ///
        ///        sc.close();
        ///
        ///		String infile,outfile;
        ///		infile=&quot;UNSPECIFIED&quot;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJavaCode {
            get {
                return ResourceManager.GetString("TestJavaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {-----------------------------------------------------------------------------
        /// Package: Trig
        /// Package: Elementary
        /// Package: Numerical
        /// Package: Lists
        /// Package: Data
        ///-----------------------------------------------------------------------------}
        ///unit uFunctions;
        ///
        ///interface
        ///
        ///uses SysUtils, Classes, uMathIntf, uMath, uMathValues, uFPUSupport, uMathConstants;
        ///
        ///type
        ///  TPackageTrig = class(TFunctionPackage)
        ///  published
        ///    function Deg2Rad_1(Context: IContext; args: TExprList): IExpression;
        ///    f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPascalCode {
            get {
                return ResourceManager.GetString("TestPascalCode", resourceCulture);
            }
        }
    }
}
